set -g mouse on
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -g history-limit 10000

# prefix
set -g prefix C-a
unbind C-b

# vi mode
setw -g mode-keys vi
set -g status-keys vi

# faster key repeat
set -g escape-time 0

# index at 1
set -g base-index 1
setw -g pane-base-index 1

# split panes
bind | split-window -h
bind - split-window -v

# vim-like pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# reload config
bind r source-file ~/.tmux.conf \; display-message "config reloaded"